// Rebuilds wiki/_index.md from article frontmatter and lints the wiki.
// Usage: node scripts/wiki.mjs          rebuild the index, report problems
//        node scripts/wiki.mjs --check  fail if the index is stale or there are problems (no writes)
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { join, relative, dirname, resolve, sep } from 'node:path'

const root = resolve(dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..', 'wiki')
const check = process.argv.includes('--check')
const sections = ['concepts', 'topics', 'references']
const articleFields = ['title', 'type', 'summary', 'confidence', 'sources', 'updated']
const rawFields = ['title', 'date', 'kind']

const walk = (dir) =>
  existsSync(dir)
    ? readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
        e.isDirectory() ? walk(join(dir, e.name)) : e.name.endsWith('.md') ? [join(dir, e.name)] : [])
    : []
const rel = (p) => relative(root, p).split(sep).join('/')

// Minimal frontmatter reader: `key: value` and `key: [a, b]` lines between --- fences.
function frontmatter(text) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---/)
  if (!m) return null
  const data = {}
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^(\w+):\s*(.*)$/)
    if (!kv) continue
    const value = kv[2].trim()
    data[kv[1]] = value.startsWith('[')
      ? value.slice(1, -1).split(',').map((s) => s.trim()).filter(Boolean)
      : value
  }
  return data
}

const problems = []
const articles = sections.flatMap((s) => walk(join(root, s))).map((path) => {
  const text = readFileSync(path, 'utf8')
  return { path, rel: rel(path), text, fm: frontmatter(text) ?? {} }
})
const raws = walk(join(root, 'raw')).map((path) => ({ path, rel: rel(path), fm: frontmatter(readFileSync(path, 'utf8')) ?? {} }))

for (const a of articles) {
  for (const f of articleFields) if (!a.fm[f] || (Array.isArray(a.fm[f]) && !a.fm[f].length)) problems.push(`${a.rel}: missing frontmatter "${f}"`)
  if (a.fm.type && !sections.includes(a.fm.type + 's')) problems.push(`${a.rel}: type "${a.fm.type}" must be concept, topic or reference`)
  if (a.fm.type && !a.rel.startsWith(a.fm.type + 's/')) problems.push(`${a.rel}: type "${a.fm.type}" does not match its folder`)
  if (a.fm.confidence && !['high', 'medium', 'low'].includes(a.fm.confidence)) problems.push(`${a.rel}: confidence must be high, medium or low`)
  for (const s of [].concat(a.fm.sources ?? [])) if (!existsSync(join(root, s))) problems.push(`${a.rel}: source not found: ${s}`)
}
for (const r of raws) for (const f of rawFields) if (!r.fm[f]) problems.push(`${r.rel}: missing frontmatter "${f}"`)

// Relative markdown links must resolve; count inbound links to find orphans.
const inbound = new Map(articles.map((a) => [a.rel, 0]))
for (const file of [...articles, { path: join(root, 'schema.md'), rel: 'schema.md' }]) {
  if (!existsSync(file.path)) continue
  // Links inside code blocks and inline code are examples, not links.
  const text = (file.text ?? readFileSync(file.path, 'utf8')).replace(/```[\s\S]*?```/g, '').replace(/`[^`\n]*`/g, '')
  for (const [, target] of text.matchAll(/\]\(([^)\s#]+\.md)(?:#[^)]*)?\)/g)) {
    if (/^[a-z]+:/i.test(target)) continue
    const abs = resolve(dirname(file.path), target)
    const r = rel(abs)
    if (!existsSync(abs)) problems.push(`${file.rel}: broken link to ${target}`)
    else if (inbound.has(r) && r !== file.rel) inbound.set(r, inbound.get(r) + 1)
  }
}
for (const [r, n] of inbound) if (n === 0) problems.push(`${r}: orphan (no other article links to it)`)

const byType = (t) => articles.filter((a) => a.fm.type === t).sort((x, y) => x.rel.localeCompare(y.rel))
const row = (a) => `| [${a.fm.title ?? a.rel}](${a.rel}) | ${a.fm.summary ?? ''} | ${a.fm.confidence ?? ''} | ${a.fm.updated ?? ''} |`
const index = [
  '# Wiki index',
  '',
  'Generated by `npm run wiki` from article frontmatter. Do not edit by hand.',
  'Rules: [schema.md](schema.md). History: [log.md](log.md).',
  '',
  ...['concept', 'topic', 'reference'].flatMap((t) => [
    `## ${t[0].toUpperCase() + t.slice(1)}s`,
    '',
    '| Article | Summary | Confidence | Updated |',
    '|---|---|---|---|',
    ...byType(t).map(row),
    '',
  ]),
  '## Raw sources',
  '',
  '| Source | Kind | Date |',
  '|---|---|---|',
  ...raws.sort((x, y) => x.rel.localeCompare(y.rel)).map((r) => `| [${r.fm.title ?? r.rel}](${r.rel}) | ${r.fm.kind ?? ''} | ${r.fm.date ?? ''} |`),
  '',
].join('\n')

const indexPath = join(root, '_index.md')
const current = existsSync(indexPath) ? readFileSync(indexPath, 'utf8').replace(/\r\n/g, '\n') : ''
if (check) {
  if (current !== index) problems.push('_index.md is stale: run npm run wiki')
} else if (current !== index) {
  writeFileSync(indexPath, index)
  console.log('Rebuilt wiki/_index.md')
}

console.log(`${articles.length} articles, ${raws.length} raw sources, ${problems.length} problems`)
for (const p of problems) console.log(`  - ${p}`)
process.exit(problems.length ? 1 : 0)
